Initial adaptation to the Technically organisation
technically-php/whitelist-container pull request #1
Opened 2021-04-28 14:52 UTC by e1himself

- Change namespace to `Technically`
- Add auto-tests with Github Actions 
- Tweak README a bit

2021-04-28 15:23 UTC, someniatko requested changes

2021-04-28 15:23 UTC, someniatko commented on .github/workflows/test.yml
> +        php: [ '8.0' ]
@e1himself I think we should test also on 7.4 as long as we support this version

2021-04-28 15:23 UTC, someniatko commented on LICENSE
> +Copyright (c) 2021 Illya Somov <someniatko@gmail.com>
I don't think it's necessary to refer to my full name, I guess the nickname is unique enough

2021-04-28 15:23 UTC, someniatko commented on README.md
> +
I've intentionally removed newline here, to aid visual corellation of the text to the header.

2021-04-28 15:23 UTC, someniatko commented on README.md
> +Implemented by [Illya Somov][https://github.com/someniatko].
please refer to me as `someniatko` instead of full name

2021-04-28 15:27 UTC, someniatko commented
Thank you for the contribution! I have zero knowledge of GitHub Actions though, will need to learn a bit.

2021-04-29 08:44 UTC, e1himself commented on README.md
> +Implemented by [Illya Somov][https://github.com/someniatko].
Fixed with 15af96288931eff3be45ea2410e89193f9855cc9

2021-04-29 08:44 UTC, e1himself commented on LICENSE
> +Copyright (c) 2021 Illya Somov <someniatko@gmail.com>
Fixed with 15af96288931eff3be45ea2410e89193f9855cc9

2021-04-29 08:44 UTC, e1himself commented on .github/workflows/test.yml
> +        php: [ '8.0' ]
Fixed with fbd536115e4727abf5afb32fecff2f9042196a09

2021-04-29 08:54 UTC, e1himself commented on README.md
> +
:man_shrugging: 

I believe this is a matter of taste and preference.

I have been following the style of the original Markdown author [John Gruber](https://daringfireball.net/projects/markdown/syntax#header) and I think it does make sense for readability in raw format.

Your style is fine too, but I suggest to keep it consistent throughout the organisation and not spend time on these "[bikeshedding](https://en.wiktionary.org/wiki/bikeshedding)" discussions :)

2021-04-29 12:53 UTC, someniatko commented on README.md
> +
@e1himself Your argument of following John Gruber's style is invalid, if you look into the [source](https://daringfireball.net/projects/markdown/syntax.text) of the page you're referring to, you'll see he puts **two** newlines before a header, and one newline after. I instead put one before and none after. I'll gladly accept 2+1 as the style guide. However, putting a single line both before and after a section violates the common sense: related stuff should visually come together.

2021-04-30 08:58 UTC, e1himself commented on README.md
> +
> I'll gladly accept 2+1 as the style guide. 

This does make sense. Changing it to 2+1. 

Thanks! :+1:

2021-04-30 08:58 UTC, e1himself commented on README.md
> +
2f66801ca950fce81c74ffae2bf0b720cc76b0da

2021-04-30 09:03 UTC, e1himself commented on README.md
> +
JFYI I have also updated other Readmes in the organisation:

- `null-container`
- `array-container`
- `dependency-resolver`

2021-04-30 17:16 UTC, someniatko approved these changes

2021-04-30 17:17 UTC, someniatko commented
@e1himself I guess it makes sense to squash these commits into one, WDYT?

2021-05-05 08:22 UTC, e1himself commented
> I guess it makes sense to squash these commits into one, WDYT?

idk, I usually never squash :shrug: 

In this case, I guess, it might make sense.

2021-05-05 08:22 UTC, merged